# QC16 -Qual é a forma de catalogação de uma obra?
# Resposta esperada: AACR2"
# Resposta esperada: Dublin Core"
# Resposta esperada: MARC 21"
PREFIX ex: <http://www.semanticweb.org/kely/ontologies/2023/11/pinakes#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?formato_de_catalogacao WHERE {
?obra a ex:Obra ;
ex:tituloProprio ?titulo ;                                               ex:formatoDeCatalogacao ?formato_de_catalogacao .
}