# QC2 -A quais obras uma determinada obra está relacionada?


# Resposta esperada: Ciência da Informação (Online)"
# Resposta esperada: Bibliografia Brasileira de Ciência da Informação"
PREFIX ex: <http://www.semanticweb.org/kely/ontologies/2023/11/pinakes#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?titulo_Relacionado WHERE {
?obra a ex:Obra ;
ex:tituloProprio ?titulo ;
ex:hasRelatedPublication ?Publicacao_Relacionada .
?Publicacao_Relacionada ex:nome ?titulo_Relacionado .
}