# QC29-Qual é a nota de suplemento de uma obra
# Resposta esperada: Tem suplemento: Wines & Vines Annual Directory (ISSN 0084-0351)."
PREFIX ex: <http://www.semanticweb.org/kely/ontologies/2023/11/pinakes#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?nota WHERE {
?obra a ex:Obra ;
ex:tituloProprio ?titulo ;
ex:hasNote ?tipo .
?tipo rdfs:label ?tipo_nota .
?tipo ex:notaDeSuplemento ?nota .
}