# QC4-Qual é a data de cadastro de uma obra?
# Resposta esperada: 2005"
PREFIX ex: <http://www.semanticweb.org/kely/ontologies/2023/11/pinakes#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?data_cadastro WHERE {
?obra a ex:Obra ;
ex:tituloProprio ?titulo;
ex:dataDeCadastro ?data_cadastro .
}