# QC42- Qual é o software utilizado pela biblioteca
# Resposta esperada: Koha"
PREFIX ex: <http://www.semanticweb.org/kely/ontologies/2023/11/pinakes#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?software WHERE {
?biblioteca a ex:Biblioteca ;
ex:softwareUtilizado ?software .
}