# QC45- Quais são os serviços utilizados pela biblioteca? 
# Resposta esperada: COMUT"
# Resposta esperada: CCN
# Resposta esperada: Bibliodata
PREFIX ex: <http://www.semanticweb.org/kely/ontologies/2023/11/pinakes#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?Servicos WHERE {
?bibloteca a ex:Biblioteca ;
ex:denominacao ?Denominacao ;
ex:servicosBiblioteca ?Servicos ;
}