# QC52-Qual é o CNPJ da instituição?
# Resposta esperada: 04.082.993/0001-49"
PREFIX ex: <http://www.semanticweb.org/kely/ontologies/2023/11/pinakes#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?CNPJ WHERE {
?instituicao a ex:Instituicao ;
ex:nome ?unidade ;
ex:cnpj ?CNPJ .
}