#  QC53-Qual é o nome da unidade?
# Resposta esperada: Coordenação de Serviços Bibliográficos"
PREFIX ex: <http://www.semanticweb.org/kely/ontologies/2023/11/pinakes#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?nome WHERE {
?unidade a ex:Unidade ;
ex:nome?nome .
}