# QC54-Qual é a sigla da unidade?
# Resposta esperada: COBIB"
PREFIX ex: <http://www.semanticweb.org/kely/ontologies/2023/11/pinakes#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?sigla WHERE {
?unidade a ex:Unidade ;
ex:nome ?nome ;
ex:sigla?sigla .
}