# QC9-Qual é a frequência de uma obra?
# Resposta esperada: Quadrimestral"
PREFIX ex: <http://www.semanticweb.org/kely/ontologies/2023/11/pinakes#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?Frequencia WHERE {
?obra a ex:Obra ;
ex:tituloProprio ?titulo ;                                               ex:frequencia ?Frequencia .
}